documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - '*.md'

github:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

toys:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/js/toys/**'
          - 'src/data/toys.json'
          - 'public/toys.json'

frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/js/frontend/**'

renderer:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/js/milkdrop/**'
          - 'src/shaders/**'

styles:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/css/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

scripts:
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**'
          - 'package.json'
          - 'bun.lock'
