const MAX_CUSTOM_WAVES = 32;
const MAX_CUSTOM_SHAPES = 32;

function createDefaultShapeSlot(index: number): Record<string, number> {
  return {
    [`shape_${index}_enabled`]: 0,
    [`shape_${index}_sides`]: 4,
    [`shape_${index}_x`]: 0.5,
    [`shape_${index}_y`]: 0.5,
    [`shape_${index}_rad`]: 0.1,
    [`shape_${index}_ang`]: 0,
    [`shape_${index}_textured`]: 0,
    [`shape_${index}_tex_zoom`]: 1,
    [`shape_${index}_tex_ang`]: 0,
    [`shape_${index}_a`]: 1,
    [`shape_${index}_r`]: 1,
    [`shape_${index}_g`]: 0,
    [`shape_${index}_b`]: 0,
    [`shape_${index}_a2`]: 0,
    [`shape_${index}_r2`]: 0,
    [`shape_${index}_g2`]: 1,
    [`shape_${index}_b2`]: 0,
    [`shape_${index}_border_a`]: 0,
    [`shape_${index}_border_r`]: 1,
    [`shape_${index}_border_g`]: 1,
    [`shape_${index}_border_b`]: 1,
    [`shape_${index}_additive`]: 0,
    [`shape_${index}_thickoutline`]: 0,
  };
}

function createDefaultCustomWaveSlot(index: number): Record<string, number> {
  return {
    [`custom_wave_${index}_enabled`]: 0,
    [`custom_wave_${index}_samples`]: 512,
    [`custom_wave_${index}_spectrum`]: 0,
    [`custom_wave_${index}_additive`]: 0,
    [`custom_wave_${index}_usedots`]: 0,
    [`custom_wave_${index}_scaling`]: 1,
    [`custom_wave_${index}_smoothing`]: 0.5,
    [`custom_wave_${index}_mystery`]: 0,
    [`custom_wave_${index}_thick`]: 0,
    [`custom_wave_${index}_x`]: 0.5,
    [`custom_wave_${index}_y`]: 0.5,
    [`custom_wave_${index}_r`]: 1,
    [`custom_wave_${index}_g`]: 1,
    [`custom_wave_${index}_b`]: 1,
    [`custom_wave_${index}_a`]: 1,
  };
}

const DEFAULT_MILKDROP_STATE: Record<string, number> = {
  fRating: 3,
  milkdrop_preset_version: 100,
  psversion: 2,
  psversion_comp: 2,
  psversion_warp: 2,
  beat_sensitivity: 0.7,
  blend_duration: 2.4,
  decay: 0.98,
  zoom: 1,
  zoomexp: 1,
  rot: 0,
  warp: 1,
  warp_scale: 1,
  cx: 0.5,
  cy: 0.5,
  sx: 1,
  sy: 1,
  dx: 0,
  dy: 0,
  warpanimspeed: 1,
  shader: 0,
  modwavealphastart: 0.75,
  modwavealphaend: 0.95,
  bmodwavealphabyvolume: 0,
  wave_mode: 0,
  wave_scale: 1,
  wave_smoothing: 0.75,
  wave_a: 0.8,
  wave_r: 1,
  wave_g: 1,
  wave_b: 1,
  wave_x: 0.5,
  wave_y: 0.5,
  wave_mystery: 0,
  wave_thick: 0,
  wave_additive: 0,
  wave_usedots: 0,
  wave_brighten: 1,
  mesh_density: 16,
  mesh_alpha: 0,
  mesh_r: 1,
  mesh_g: 1,
  mesh_b: 1,
  bg_r: 0,
  bg_g: 0,
  bg_b: 0,
  brighten: 0,
  darken: 0,
  darken_center: 0,
  solarize: 0,
  invert: 0,
  red_blue_stereo: 0,
  gammaadj: 2,
  video_echo_enabled: 0,
  video_echo_alpha: 0,
  video_echo_zoom: 2,
  video_echo_orientation: 0,
  ob_size: 0.01,
  ob_r: 0,
  ob_g: 0,
  ob_b: 0,
  ob_a: 0,
  ib_size: 0.01,
  ib_r: 0.25,
  ib_g: 0.25,
  ib_b: 0.25,
  ib_a: 0,
  texture_wrap: 1,
  feedback_texture: 0,
  ob_border: 0,
  ib_border: 0,
  motion_vectors: 0,
  motion_vectors_x: 12,
  motion_vectors_y: 9,
  mv_dx: 0,
  mv_dy: 0,
  mv_l: 0.9,
  mv_r: 1,
  mv_g: 1,
  mv_b: 1,
  mv_a: 0,
  ...Object.fromEntries(
    Array.from({ length: MAX_CUSTOM_SHAPES }, (_, index) =>
      Object.entries(createDefaultShapeSlot(index + 1)),
    ).flat(),
  ),
  ...Object.fromEntries(
    Array.from({ length: MAX_CUSTOM_WAVES }, (_, index) =>
      Object.entries(createDefaultCustomWaveSlot(index + 1)),
    ).flat(),
  ),
};

export {
  createDefaultCustomWaveSlot,
  createDefaultShapeSlot,
  DEFAULT_MILKDROP_STATE,
  MAX_CUSTOM_SHAPES,
  MAX_CUSTOM_WAVES,
};
