// E2E Testing on Edge (Worker) — generated by tech-tree
import { test, expect } from '@playwright/test';

const BASE = process.env.DEPLOY_URL || 'http://localhost:8787';

test('deploy and verify landing page', async ({ page }) => {
  await page.goto(BASE);
  await expect(page.locator('h1')).toBeVisible();
});

test('API health check', async ({ request }) => {
  const res = await request.get(`${BASE}/api/health`);
  expect(res.status()).toBe(200);
});
