/* This file is auto-generated by scripts/generate-toy-manifest.ts. */
import type { ToyManifest } from './toy-schema.ts';

export const toyManifest: ToyManifest = [
  {
    "slug": "3dtoy",
    "title": "3D Toy",
    "description": "A twisting MilkDrop tunnel preset with chrome hues, orbiting mesh, and audio-driven spin.",
    "module": "assets/js/toys/3dtoy.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "energetic",
      "immersive"
    ],
    "tags": [
      "tunnel",
      "3d",
      "legacy"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the 3D Toy preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "3dtoy",
      "label": "3D Toy preset",
      "description": "Loads the curated 3D Toy preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "aurora-painter",
    "title": "Aurora Painter",
    "description": "A flowing aurora preset with drag-steered ribbons, pinch bloom, and rotate-to-switch color moods.",
    "module": "assets/js/toys/aurora-painter.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "featuredRank": 1,
    "moods": [
      "dreamy",
      "ethereal",
      "luminous"
    ],
    "tags": [
      "aurora",
      "ribbons",
      "gestural",
      "touch"
    ],
    "controls": [
      "Drag drift + pinch bloom + rotate moods",
      "Quick preset + color mood buttons",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Aurora Painter preset, drag to steer the ribbons, pinch to swell the glow, then rotate or use Color Mood buttons to switch palettes.",
    "starterPreset": {
      "id": "aurora-painter",
      "label": "Aurora Painter preset",
      "description": "Loads the curated Aurora Painter preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Color mood buttons",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "clay",
    "title": "Pottery Wheel Sculptor",
    "description": "An earthy sculptural preset with kiln-glow waves, grounded motion, and slow reactive pulses.",
    "module": "assets/js/toys/clay.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "focus",
      "tactile"
    ],
    "tags": [
      "sculpting",
      "pottery",
      "3d"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Pottery Wheel Sculptor preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "clay",
      "label": "Pottery Wheel Sculptor preset",
      "description": "Loads the curated Pottery Wheel Sculptor preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "evol",
    "title": "Evolutionary Weirdcore",
    "description": "A glitch-fractal preset that mutates between weirdcore colors, warped mesh lines, and unstable beat flashes.",
    "module": "assets/js/toys/evol.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "psychedelic",
      "cosmic"
    ],
    "tags": [
      "fractal",
      "glitch",
      "evolutionary"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Evolutionary Weirdcore preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "evol",
      "label": "Evolutionary Weirdcore preset",
      "description": "Loads the curated Evolutionary Weirdcore preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "geom",
    "title": "Microphone Geometry Visualizer",
    "description": "A geometry-first preset with crisp polygons, reactive rings, and shifting symmetry.",
    "module": "assets/js/toys/geom.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "energetic",
      "immersive"
    ],
    "tags": [
      "geometry",
      "microphone",
      "reactive"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Microphone Geometry Visualizer preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "geom",
      "label": "Microphone Geometry Visualizer preset",
      "description": "Loads the curated Microphone Geometry Visualizer preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "holy",
    "title": "Halo Visualizer",
    "description": "A halo preset with luminous rings, suspended shapes, and gentle audio-driven bloom.",
    "module": "assets/js/toys/holy.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "serene",
      "ethereal"
    ],
    "tags": [
      "halos",
      "particles",
      "ambient"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Halo Visualizer preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "holy",
      "label": "Halo Visualizer preset",
      "description": "Loads the curated Halo Visualizer preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "multi",
    "title": "Multi-Capability Visualizer",
    "description": "A hybrid preset that folds the old multi-capability vibe into one dense, reactive MilkDrop scene.",
    "module": "assets/js/toys/multi.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "energetic",
      "cosmic"
    ],
    "tags": [
      "motion",
      "hybrid",
      "immersive"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Multi-Capability Visualizer preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "multi",
      "label": "Multi-Capability Visualizer preset",
      "description": "Loads the curated Multi-Capability Visualizer preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "seary",
    "title": "Synesthetic Visualizer",
    "description": "A synesthetic pattern preset with mapped color shifts, looping forms, and responsive movement.",
    "module": "assets/js/toys/seary.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "dreamy",
      "immersive"
    ],
    "tags": [
      "synesthetic",
      "patterns",
      "audio-mapped"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Synesthetic Visualizer preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "seary",
      "label": "Synesthetic Visualizer preset",
      "description": "Loads the curated Synesthetic Visualizer preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "legible",
    "title": "Terminal Word Grid",
    "description": "A retro terminal preset with grid-like mesh lines, phosphor greens, and measured pulse trails.",
    "module": "assets/js/toys/legible.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "focus",
      "minimal"
    ],
    "tags": [
      "text",
      "retro",
      "grid"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Terminal Word Grid preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "legible",
      "label": "Terminal Word Grid preset",
      "description": "Loads the curated Terminal Word Grid preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "symph",
    "title": "Spectrograph",
    "description": "A spectrograph-inspired preset with calm bands, soft trails, and readable music response.",
    "module": "assets/js/toys/symph.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "calming",
      "serene"
    ],
    "tags": [
      "spectrograph",
      "ambient",
      "calming"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Spectrograph preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "symph",
      "label": "Spectrograph preset",
      "description": "Loads the curated Spectrograph preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "cube-wave",
    "title": "Grid Visualizer",
    "description": "A grid preset with drag-steered wave drift, pinch energy lift, and rotate-to-switch grid modes.",
    "module": "assets/js/toys/cube-wave.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "pulsing",
      "energetic"
    ],
    "tags": [
      "grid",
      "waves",
      "mode-switch",
      "gestural"
    ],
    "controls": [
      "Drag drift + pinch lift + rotate modes",
      "Grid mode buttons",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Grid Visualizer preset, drag to steer the drift, pinch to lift the energy, then rotate or use Grid Mode buttons to switch feels.",
    "starterPreset": {
      "id": "cube-wave",
      "label": "Grid Visualizer preset",
      "description": "Loads the curated Grid Visualizer preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Grid mode buttons",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "bubble-harmonics",
    "title": "Bubble Harmonics",
    "description": "A bubble preset with translucent rings, harmonic pulse motion, and bright high-end shimmer.",
    "module": "assets/js/toys/bubble-harmonics.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "featuredRank": 7,
    "moods": [
      "playful",
      "uplifting"
    ],
    "tags": [
      "bubbles",
      "harmonics",
      "reactive"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Bubble Harmonics preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "bubble-harmonics",
      "label": "Bubble Harmonics preset",
      "description": "Loads the curated Bubble Harmonics preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "pocket-pulse",
    "title": "Pocket Pulse",
    "description": "A compact pulse preset with touch-steered center drift, tap-triggered lift, and quick reactive glow.",
    "module": "assets/js/toys/pocket-pulse.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "prototype",
    "moods": [
      "uplifting",
      "focus",
      "minimal"
    ],
    "tags": [
      "mobile",
      "pulses",
      "touch"
    ],
    "controls": [
      "Touch drag steering + tap accents",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Pocket Pulse preset, then drag to steer the pulse center and tap to spike the glow before refining Blend or source fields.",
    "starterPreset": {
      "id": "pocket-pulse",
      "label": "Pocket Pulse preset",
      "description": "Loads the curated Pocket Pulse preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "mobile-ripples",
    "title": "Mobile Ripples",
    "description": "A low-motion ripple preset with touch-steered drift, press-responsive ring growth, and lightweight audio response.",
    "module": "assets/js/toys/mobile-ripples.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "prototype",
    "moods": [
      "calming",
      "focus",
      "glow"
    ],
    "tags": [
      "mobile",
      "ripples",
      "touch"
    ],
    "controls": [
      "Touch drag steering",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Mobile Ripples preset, then drag to drift the ripple center and hold touch to widen the rings before adjusting Blend.",
    "starterPreset": {
      "id": "mobile-ripples",
      "label": "Mobile Ripples preset",
      "description": "Loads the curated Mobile Ripples preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "juke-grid",
    "title": "Juke Grid",
    "description": "A chopped grid preset with touch-steered lane snaps, razor mesh lines, and footwork-ready energy.",
    "module": "assets/js/toys/juke-grid.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "prototype",
    "moods": [
      "energetic",
      "focus",
      "pulsing"
    ],
    "tags": [
      "grid",
      "glitch",
      "touch",
      "reactive"
    ],
    "controls": [
      "Touch drag lane steering",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Juke Grid preset, then drag across the screen to shove lane offsets and sharpen the chop energy before tuning Blend.",
    "starterPreset": {
      "id": "juke-grid",
      "label": "Juke Grid preset",
      "description": "Loads the curated Juke Grid preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "heel-toe-comets",
    "title": "Heel-Toe Comets",
    "description": "A diagonal comet preset with touch-aimed lane drift, rapid streaks, and rush-forward depth.",
    "module": "assets/js/toys/heel-toe-comets.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "prototype",
    "moods": [
      "energetic",
      "immersive",
      "pulsing"
    ],
    "tags": [
      "particles",
      "pulses",
      "touch",
      "reactive"
    ],
    "controls": [
      "Touch drag lane steering",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Heel-Toe Comets preset, then drag to angle the comet lanes and hold touch to increase rush depth before tweaking Blend.",
    "starterPreset": {
      "id": "heel-toe-comets",
      "label": "Heel-Toe Comets preset",
      "description": "Loads the curated Heel-Toe Comets preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "battle-fan",
    "title": "Battle Fan",
    "description": "A radial fan preset with touch-steered burst center, kick-snare flips, and fast reactive color changes.",
    "module": "assets/js/toys/battle-fan.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "prototype",
    "moods": [
      "energetic",
      "pulsing",
      "immersive"
    ],
    "tags": [
      "burst",
      "patterns",
      "touch",
      "reactive"
    ],
    "controls": [
      "Touch drag fan steering",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Battle Fan preset, then drag to move the fan center and spike burst intensity with quick touch motion before adjusting Blend.",
    "starterPreset": {
      "id": "battle-fan",
      "label": "Battle Fan preset",
      "description": "Loads the curated Battle Fan preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "cosmic-particles",
    "title": "Cosmic Particles",
    "description": "A cosmic preset with drag-steered orbit drift, pinch depth lift, and rotate-to-switch cosmic modes.",
    "module": "assets/js/toys/cosmic-particles.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "featuredRank": 5,
    "moods": [
      "cosmic",
      "immersive"
    ],
    "tags": [
      "particles",
      "nebula",
      "swirl",
      "gestural"
    ],
    "controls": [
      "Drag drift + pinch depth + rotate modes",
      "Cosmic preset buttons",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Cosmic Particles preset, drag to steer the orbit, pinch to deepen the pull, then rotate or use Cosmic Preset buttons to switch modes.",
    "starterPreset": {
      "id": "cosmic-particles",
      "label": "Cosmic Particles preset",
      "description": "Loads the curated Cosmic Particles preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Cosmic preset buttons",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "lights",
    "title": "Audio Light Show",
    "description": "A lighting preset with bright palette sweeps, layered glow, and punchy audio-driven contrast.",
    "module": "assets/js/toys/lights.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "energetic",
      "luminous"
    ],
    "tags": [
      "lights",
      "shader",
      "palette"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Audio Light Show preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "lights",
      "label": "Audio Light Show preset",
      "description": "Loads the curated Audio Light Show preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "spiral-burst",
    "title": "Spiral Burst",
    "description": "A spiral preset with drag-steered spin, pinch burst lift, and rotate-to-cycle palettes.",
    "module": "assets/js/toys/spiral-burst.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "featuredRank": 4,
    "moods": [
      "energetic",
      "pulsing",
      "cosmic"
    ],
    "tags": [
      "spirals",
      "burst",
      "gestural"
    ],
    "controls": [
      "Drag spin + pinch burst + rotate palettes",
      "Spiral mode + palette buttons",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Spiral Burst preset, drag to torque the spin, pinch to intensify the burst, then rotate or use Spiral controls to change the feel.",
    "starterPreset": {
      "id": "spiral-burst",
      "label": "Spiral Burst preset",
      "description": "Loads the curated Spiral Burst preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Spiral mode buttons",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "rainbow-tunnel",
    "title": "Rainbow Tunnel",
    "description": "A tunnel preset with drag-steered drift, pinch speed lift, and rotate-to-cycle color modes.",
    "module": "assets/js/toys/rainbow-tunnel.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "cosmic",
      "drifting"
    ],
    "tags": [
      "tunnel",
      "rainbow",
      "immersive",
      "gestural"
    ],
    "controls": [
      "Drag drift + pinch speed + rotate palettes",
      "Motion mode + color drift buttons",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Rainbow Tunnel preset, drag to steer the tunnel, pinch to increase speed, then rotate or use Color Drift buttons to cycle the palette.",
    "starterPreset": {
      "id": "rainbow-tunnel",
      "label": "Rainbow Tunnel preset",
      "description": "Loads the curated Rainbow Tunnel preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Color drift buttons",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "star-field",
    "title": "Star Field",
    "description": "A star field preset with drag-steered drift, pinch sparkle lift, and rotate-to-cycle sky palettes.",
    "module": "assets/js/toys/star-field.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "serene",
      "drifting",
      "celestial"
    ],
    "tags": [
      "stars",
      "nebula",
      "gestural"
    ],
    "controls": [
      "Drag drift + pinch sparkle + rotate palettes",
      "Sky intensity + palette buttons",
      "Pulse meter",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Star Field preset, drag to steer drift, pinch to lift sparkle, then rotate or use Sky Palette buttons while watching the pulse meter.",
    "starterPreset": {
      "id": "star-field",
      "label": "Star Field preset",
      "description": "Loads the curated Star Field preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Sky palette buttons",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "fractal-kite-garden",
    "title": "Fractal Kite Garden",
    "description": "A kite-garden preset with branching polygon clusters, soft sway, and airy shimmer.",
    "module": "assets/js/toys/fractal-kite-garden.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "archived",
    "moods": [
      "dreamy",
      "serene"
    ],
    "tags": [
      "fractal",
      "kite",
      "generative"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Fractal Kite Garden preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "fractal-kite-garden",
      "label": "Fractal Kite Garden preset",
      "description": "Loads the curated Fractal Kite Garden preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "tactile-sand-table",
    "title": "Tactile Sand Table",
    "description": "A sand-table preset with earthy ripples, tilt-steered gravity, and grounded reactive texture.",
    "module": "assets/js/toys/tactile-sand-table.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "featuredRank": 3,
    "moods": [
      "calming",
      "grounded"
    ],
    "tags": [
      "sand",
      "tilt",
      "haptics",
      "motion"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export",
      "Motion controls (enable tilt, lock gravity, re-center)"
    ],
    "firstRunHint": "Start with the Tactile Sand Table preset, enable tilt control in Gravity settings, then lock or re-center gravity as needed.",
    "starterPreset": {
      "id": "tactile-sand-table",
      "label": "Tactile Sand Table preset",
      "description": "Loads the curated Tactile Sand Table preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Tilt gravity controls",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": true
    }
  },
  {
    "slug": "bioluminescent-tidepools",
    "title": "Bioluminescent Tidepools",
    "description": "A tidepool preset with drag-shaped currents, pinch lift, and rotate-to-cycle moods.",
    "module": "assets/js/toys/bioluminescent-tidepools.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "featuredRank": 2,
    "moods": [
      "serene",
      "ethereal",
      "fiery",
      "dreamy"
    ],
    "tags": [
      "ocean",
      "bioluminescent",
      "caustics",
      "gestural"
    ],
    "controls": [
      "Drag currents + pinch lift + rotate moods",
      "Tidepool mood + current buttons",
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Bioluminescent Tidepools preset, drag to shape the currents, pinch to brighten the pool, then rotate or use Tidepool Mood buttons to shift the scene.",
    "starterPreset": {
      "id": "bioluminescent-tidepools",
      "label": "Bioluminescent Tidepools preset",
      "description": "Loads the curated Bioluminescent Tidepools preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Tidepool mood buttons",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "neon-wave",
    "title": "Neon Wave",
    "description": "A synthwave preset with horizon glow, neon mesh movement, and saturated beat response.",
    "module": "assets/js/toys/neon-wave.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "featuredRank": 6,
    "moods": [
      "energetic",
      "immersive"
    ],
    "tags": [
      "synthwave",
      "cyberpunk",
      "retro",
      "visualizer",
      "bloom"
    ],
    "controls": [
      "Preset browser + favorites",
      "Blend duration + autoplay/random",
      "Live source editor + import/export"
    ],
    "firstRunHint": "Start with the Neon Wave preset, then use Blend for slower transitions or open the source editor to push the palette and motion further.",
    "starterPreset": {
      "id": "neon-wave",
      "label": "Neon Wave preset",
      "description": "Loads the curated Neon Wave preset inside the shared MilkDrop runtime."
    },
    "wowControl": "Live source editor",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  },
  {
    "slug": "milkdrop",
    "title": "MilkDrop Visualizer",
    "description": "Preset-driven feedback visualizer with blend transitions, live source editing, and import/export flows.",
    "module": "assets/js/toys/milkdrop-toy.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "moods": [
      "immersive",
      "psychedelic"
    ],
    "tags": [
      "feedback",
      "warp",
      "visualizer",
      "retro",
      "presets",
      "editor"
    ],
    "controls": [
      "Preset browser + favorites/recent",
      "Blend duration + autoplay/random",
      "Live source editor + diagnostics",
      "Import/export preset files",
      "Quality presets"
    ],
    "firstRunHint": "Start with the curated preset browser, then toggle autoplay to hear smooth blend transitions.",
    "starterPreset": {
      "id": "aurora-feedback-core",
      "label": "aurora feedback starter",
      "description": "Balanced feedback and blend settings for a quick first run."
    },
    "wowControl": "Preset browser",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  }
];

export default toyManifest;
