/* This file is auto-generated by scripts/generate-toy-manifest.ts. */
import type { ToyManifest } from './toy-schema.ts';

export const toyManifest: ToyManifest = [
  {
    "slug": "milkdrop",
    "title": "MilkDrop Visualizer",
    "description": "MilkDrop-inspired browser visualizer with demo audio, hand-picked favorites, live editing, and preset import/export.",
    "module": "assets/js/toys/milkdrop-toy.ts",
    "type": "module",
    "requiresWebGPU": true,
    "allowWebGLFallback": true,
    "lifecycleStage": "featured",
    "moods": [
      "immersive",
      "psychedelic"
    ],
    "tags": [
      "feedback",
      "warp",
      "visualizer",
      "retro",
      "presets",
      "editor"
    ],
    "controls": [
      "Browse the lineup",
      "Try autoplay or random",
      "Edit preset code and see the scene respond live",
      "Bring in or save preset files",
      "Tune quality for smoother or richer playback"
    ],
    "touchHints": [
      "Drag to bend the scene and shove the feedback trail.",
      "Pinch to swell or compress the depth and intensity.",
      "Rotate with two fingers to twist the whole image."
    ],
    "firstRunHint": "Open the lineup, then try autoplay.",
    "starterPreset": {
      "id": "rovastar-parallel-universe",
      "label": "easy opener",
      "description": "An easy first pick with the classic feedback glow."
    },
    "wowControl": "Browse looks",
    "recommendedCapability": "demoAudio",
    "capabilities": {
      "microphone": true,
      "demoAudio": true,
      "motion": false
    }
  }
];

export default toyManifest;
