/**
 * Transpiles the JavaScript equation strings shipped in `butterchurn-presets`
 * back into MilkDrop EEL source.
 *
 * The upstream `presets/converted/*.json` payloads store preset equations only
 * as minified JavaScript (`a.zoom+=.1*a.rad*a.q1;`). MilkDrop `.milk` files
 * store them as EEL (`per_frame_1=zoom = zoom + 0.1*rad*q1;`), which is what
 * this repository's compiler, VM, and preset editor consume. Without this
 * conversion an imported preset keeps its base values and shaders but loses
 * every per-frame, per-pixel, per-point, and per-shape equation.
 *
 * The JavaScript is machine generated by butterchurn's own EEL-to-JS pass and
 * then minified, so the accepted grammar is deliberately narrow: expression
 * statements, comma sequences, assignments (including compound assignment),
 * ternaries, the usual arithmetic/comparison/logical operators, calls into a
 * fixed intrinsic set, and `a.name` / `a["name"]` / `a.megabuf[expr]` accesses.
 * Anything outside that subset (loops, local variable declarations, unknown
 * intrinsics) is reported as unsupported rather than silently mistranslated.
 */

export type TranspileResult =
  | { ok: true; statements: string[] }
  | { ok: false; reason: string };

type Token =
  | { type: 'number'; value: string }
  | { type: 'identifier'; value: string }
  | { type: 'string'; value: string }
  | { type: 'punct'; value: string }
  | { type: 'eof'; value: '' };

type Node =
  | { type: 'number'; value: number }
  | { type: 'variable'; name: string }
  | { type: 'megabuf'; buffer: 'megabuf' | 'gmegabuf'; index: Node }
  | { type: 'unary'; operator: string; operand: Node }
  | { type: 'binary'; operator: string; left: Node; right: Node }
  | { type: 'conditional'; test: Node; consequent: Node; alternate: Node }
  | { type: 'call'; name: string; args: Node[] }
  | { type: 'assign'; operator: string; target: Node; value: Node };

class TranspileError extends Error {}

const SCOPE_MARKER = ' scope';
const MATH_MARKER = ' math';
const CALL_PREFIX = ' call:';
const BUFFER_PREFIX = ' buffer:';
const SEQUENCE_CALL = '__sequence';

const PUNCTUATORS = [
  '>>>=',
  '===',
  '!==',
  '**=',
  '<<=',
  '>>=',
  '>>>',
  '==',
  '!=',
  '<=',
  '>=',
  '&&',
  '||',
  '++',
  '--',
  '+=',
  '-=',
  '*=',
  '/=',
  '%=',
  '**',
  '<<',
  '>>',
  '(',
  ')',
  '[',
  ']',
  '{',
  '}',
  ',',
  ';',
  '?',
  ':',
  '.',
  '+',
  '-',
  '*',
  '/',
  '%',
  '<',
  '>',
  '=',
  '!',
  '&',
  '|',
  '^',
  '~',
];

/** JavaScript call targets mapped to their MilkDrop EEL equivalent. */
const CALL_MAP: Record<string, string> = {
  'Math.sin': 'sin',
  'Math.cos': 'cos',
  'Math.tan': 'tan',
  'Math.asin': 'asin',
  'Math.acos': 'acos',
  'Math.atan': 'atan',
  'Math.atan2': 'atan2',
  'Math.abs': 'abs',
  'Math.floor': 'floor',
  'Math.ceil': 'ceil',
  'Math.min': 'min',
  'Math.max': 'max',
  'Math.log': 'log',
  'Math.exp': 'exp',
  'Math.sqrt': 'sqrt',
  'Math.pow': 'pow',
  'Math.sign': 'sign',
  abs: 'abs',
  above: 'above',
  band: 'band',
  below: 'below',
  bitand: 'band',
  bitor: 'bor',
  bnot: 'bnot',
  bor: 'bor',
  ceil: 'ceil',
  cos: 'cos',
  equal: 'equal',
  exp: 'exp',
  floor: 'floor',
  int: 'int',
  log: 'log',
  log10: 'log10',
  max: 'max',
  min: 'min',
  mod: 'mod',
  pow: 'pow',
  rand: 'rand',
  randint: 'randint',
  sigmoid: 'sigmoid',
  sign: 'sign',
  sin: 'sin',
  sqr: 'sqr',
  sqrt: 'sqrt',
  tan: 'tan',
};

const BINARY_PRECEDENCE: Record<string, number> = {
  '||': 1,
  '&&': 2,
  '|': 3,
  '&': 5,
  '==': 6,
  '!=': 6,
  '===': 6,
  '!==': 6,
  '<': 7,
  '>': 7,
  '<=': 7,
  '>=': 7,
  '+': 9,
  '-': 9,
  '*': 10,
  '/': 10,
  '%': 10,
};

const EEL_OPERATORS: Record<string, string> = {
  '||': '||',
  '&&': '&&',
  '|': '|',
  '&': '&',
  '==': '==',
  '!=': '!=',
  '===': '==',
  '!==': '!=',
  '<': '<',
  '>': '>',
  '<=': '<=',
  '>=': '>=',
  '+': '+',
  '-': '-',
  '*': '*',
  '/': '/',
  '%': '%',
};

const ASSIGN_OPERATORS = new Set(['=', '+=', '-=', '*=', '/=', '%=']);

const UNSUPPORTED_KEYWORDS = [
  'var',
  'let',
  'const',
  'for',
  'while',
  'do',
  'if',
  'function',
  'return',
];

const NUMBER_PATTERN =
  /^(?:0[xX][0-9a-fA-F]+|(?:[0-9]*\.)?[0-9]+(?:[eE][+-]?[0-9]+)?)/u;
const IDENTIFIER_PATTERN = /^[A-Za-z_][A-Za-z0-9_]*$/u;

function tokenize(source: string): Token[] {
  const tokens: Token[] = [];
  let index = 0;

  while (index < source.length) {
    const char = source[index] as string;

    if (/\s/u.test(char)) {
      index += 1;
      continue;
    }

    if (char === '"' || char === "'") {
      const quote = char;
      let value = '';
      index += 1;
      while (index < source.length && source[index] !== quote) {
        if (source[index] === '\\') {
          value += source[index + 1] ?? '';
          index += 2;
          continue;
        }
        value += source[index];
        index += 1;
      }
      index += 1;
      tokens.push({ type: 'string', value });
      continue;
    }

    const startsNumber =
      /[0-9]/u.test(char) ||
      (char === '.' && /[0-9]/u.test(source[index + 1] ?? ''));
    if (startsNumber) {
      const match = NUMBER_PATTERN.exec(source.slice(index));
      if (!match) {
        throw new TranspileError(`Unparseable number at offset ${index}`);
      }
      tokens.push({ type: 'number', value: match[0] });
      index += match[0].length;
      continue;
    }

    if (/[A-Za-z_$]/u.test(char)) {
      const match = /^[A-Za-z_$][A-Za-z0-9_$]*/u.exec(source.slice(index));
      const value = match?.[0] ?? char;
      tokens.push({ type: 'identifier', value });
      index += value.length;
      continue;
    }

    const punctuator = PUNCTUATORS.find((candidate) =>
      source.startsWith(candidate, index),
    );
    if (!punctuator) {
      throw new TranspileError(
        `Unexpected character "${char}" at offset ${index}`,
      );
    }
    tokens.push({ type: 'punct', value: punctuator });
    index += punctuator.length;
  }

  tokens.push({ type: 'eof', value: '' });
  return tokens;
}

class Parser {
  private position = 0;

  constructor(private readonly tokens: Token[]) {}

  private peek(offset = 0): Token {
    return this.tokens[this.position + offset] ?? { type: 'eof', value: '' };
  }

  private next(): Token {
    const token = this.peek();
    this.position += 1;
    return token;
  }

  private isPunct(value: string, offset = 0) {
    const token = this.peek(offset);
    return token.type === 'punct' && token.value === value;
  }

  private expectPunct(value: string) {
    if (!this.isPunct(value)) {
      throw new TranspileError(
        `Expected "${value}" but found "${this.peek().value}"`,
      );
    }
    this.position += 1;
  }

  /** Parses the top level as a flat list of statements. */
  parseProgram(): Node[] {
    const statements: Node[] = [];
    while (this.peek().type !== 'eof') {
      if (this.isPunct(';')) {
        this.position += 1;
        continue;
      }
      const token = this.peek();
      if (
        token.type === 'identifier' &&
        UNSUPPORTED_KEYWORDS.includes(token.value)
      ) {
        throw new TranspileError(
          `Unsupported statement keyword "${token.value}"`,
        );
      }
      if (this.isPunct('{')) {
        throw new TranspileError('Unsupported block statement');
      }
      statements.push(this.parseExpression());
      if (this.isPunct(';')) {
        this.position += 1;
      }
    }
    return statements;
  }

  private parseExpression(): Node {
    const first = this.parseAssignment();
    if (!this.isPunct(',')) {
      return first;
    }
    const sequence: Node[] = [first];
    while (this.isPunct(',')) {
      this.position += 1;
      sequence.push(this.parseAssignment());
    }
    return { type: 'call', name: SEQUENCE_CALL, args: sequence };
  }

  private parseAssignment(): Node {
    const left = this.parseConditional();
    const token = this.peek();
    if (token.type === 'punct' && ASSIGN_OPERATORS.has(token.value)) {
      this.position += 1;
      const value = this.parseAssignment();
      return { type: 'assign', operator: token.value, target: left, value };
    }
    return left;
  }

  private parseConditional(): Node {
    const test = this.parseBinary(0);
    if (!this.isPunct('?')) {
      return test;
    }
    this.position += 1;
    const consequent = this.parseAssignment();
    this.expectPunct(':');
    const alternate = this.parseAssignment();
    return { type: 'conditional', test, consequent, alternate };
  }

  private parseBinary(minPrecedence: number): Node {
    let left = this.parseUnary();
    for (;;) {
      const token = this.peek();
      if (token.type !== 'punct') {
        break;
      }
      const precedence = BINARY_PRECEDENCE[token.value];
      if (precedence === undefined || precedence < minPrecedence) {
        break;
      }
      this.position += 1;
      const right = this.parseBinary(precedence + 1);
      left = { type: 'binary', operator: token.value, left, right };
    }
    return left;
  }

  private parseUnary(): Node {
    const token = this.peek();
    if (
      token.type === 'punct' &&
      (token.value === '-' || token.value === '+' || token.value === '!')
    ) {
      this.position += 1;
      return {
        type: 'unary',
        operator: token.value,
        operand: this.parseUnary(),
      };
    }
    if (
      token.type === 'punct' &&
      (token.value === '++' || token.value === '--')
    ) {
      throw new TranspileError('Unsupported increment operator');
    }
    return this.parseCallOrMember();
  }

  private parseCallOrMember(): Node {
    let node = this.parsePrimary();

    for (;;) {
      if (this.isPunct('.')) {
        this.position += 1;
        const property = this.next();
        if (property.type !== 'identifier') {
          throw new TranspileError('Expected property name after "."');
        }
        node = this.applyMember(node, property.value);
        continue;
      }
      if (this.isPunct('[')) {
        this.position += 1;
        const index = this.parseAssignment();
        this.expectPunct(']');
        node = this.applyComputedMember(node, index);
        continue;
      }
      if (this.isPunct('(')) {
        node = this.applyCall(node);
        continue;
      }
      break;
    }

    return node;
  }

  private applyMember(node: Node, property: string): Node {
    if (node.type === 'variable' && node.name === SCOPE_MARKER) {
      if (property === 'megabuf' || property === 'gmegabuf') {
        return { type: 'variable', name: `${BUFFER_PREFIX}${property}` };
      }
      return { type: 'variable', name: property };
    }
    if (node.type === 'variable' && node.name === MATH_MARKER) {
      return { type: 'variable', name: `${CALL_PREFIX}Math.${property}` };
    }
    throw new TranspileError(`Unsupported member access ".${property}"`);
  }

  private applyComputedMember(node: Node, index: Node): Node {
    if (node.type === 'variable' && node.name.startsWith(BUFFER_PREFIX)) {
      const buffer = node.name.slice(BUFFER_PREFIX.length) as
        | 'megabuf'
        | 'gmegabuf';
      return { type: 'megabuf', buffer, index };
    }
    throw new TranspileError('Unsupported computed member access');
  }

  private applyCall(callee: Node): Node {
    this.expectPunct('(');
    const args: Node[] = [];
    if (!this.isPunct(')')) {
      args.push(this.parseAssignment());
      while (this.isPunct(',')) {
        this.position += 1;
        args.push(this.parseAssignment());
      }
    }
    this.expectPunct(')');

    if (callee.type !== 'variable') {
      throw new TranspileError('Unsupported call target');
    }
    const name = callee.name.startsWith(CALL_PREFIX)
      ? callee.name.slice(CALL_PREFIX.length)
      : callee.name;
    return { type: 'call', name, args };
  }

  private parsePrimary(): Node {
    const token = this.next();

    if (token.type === 'number') {
      const value = Number(token.value);
      if (!Number.isFinite(value)) {
        throw new TranspileError(
          `Unsupported numeric literal "${token.value}"`,
        );
      }
      return { type: 'number', value };
    }

    if (token.type === 'punct' && token.value === '(') {
      const expression = this.parseExpression();
      this.expectPunct(')');
      return expression;
    }

    if (token.type === 'identifier') {
      if (token.value === 'a') {
        // `a["const"]` is emitted for names that collide with JS keywords.
        if (this.isPunct('[')) {
          this.position += 1;
          const key = this.next();
          if (key.type !== 'string') {
            throw new TranspileError('Unsupported computed scope access');
          }
          this.expectPunct(']');
          return { type: 'variable', name: key.value };
        }
        return { type: 'variable', name: SCOPE_MARKER };
      }
      if (token.value === 'Math') {
        return { type: 'variable', name: MATH_MARKER };
      }
      if (token.value === 'Infinity' || token.value === 'NaN') {
        throw new TranspileError(`Unsupported literal "${token.value}"`);
      }
      return { type: 'variable', name: `${CALL_PREFIX}${token.value}` };
    }

    throw new TranspileError(`Unexpected token "${token.value}"`);
  }
}

function formatNumber(value: number): string {
  if (Number.isInteger(value) && Math.abs(value) < 1e15) {
    return String(value);
  }
  const text = String(value);
  if (!text.includes('e') && !text.includes('E')) {
    return text;
  }
  return value.toFixed(12).replace(/0+$/u, '').replace(/\.$/u, '.0');
}

/** Binds tighter than every binary operator, so operands stay parenthesised. */
const UNARY_PRECEDENCE = 20;

/**
 * Emits EEL text for `node`, parenthesising only where the surrounding
 * precedence requires it. The generated equations are shown verbatim in the
 * preset editor, so redundant parentheses are worth avoiding.
 */
function emitExpression(node: Node, minPrecedence = 0): string {
  switch (node.type) {
    case 'number':
      return formatNumber(node.value);
    case 'variable': {
      if (!IDENTIFIER_PATTERN.test(node.name)) {
        throw new TranspileError(`Unsupported identifier "${node.name.trim()}"`);
      }
      return node.name;
    }
    case 'megabuf':
      return `${node.buffer}(${emitExpression(node.index)})`;
    case 'unary':
      return `${node.operator}${emitExpression(node.operand, UNARY_PRECEDENCE)}`;
    case 'binary': {
      const operator = EEL_OPERATORS[node.operator];
      const precedence = BINARY_PRECEDENCE[node.operator];
      if (!operator || precedence === undefined) {
        throw new TranspileError(`Unsupported operator "${node.operator}"`);
      }
      const text = `${emitExpression(node.left, precedence)} ${operator} ${emitExpression(node.right, precedence + 1)}`;
      return precedence < minPrecedence ? `(${text})` : text;
    }
    case 'conditional':
      return `if(${emitExpression(node.test)}, ${emitExpression(node.consequent)}, ${emitExpression(node.alternate)})`;
    case 'call': {
      if (node.name === SEQUENCE_CALL) {
        throw new TranspileError(
          'Unsupported comma expression in value position',
        );
      }
      // butterchurn's guarded division helper; EEL division already yields 0
      // for a zero divisor in this runtime.
      if (node.name === 'div') {
        if (node.args.length !== 2) {
          throw new TranspileError('Unsupported div() arity');
        }
        const divide = BINARY_PRECEDENCE['/'] as number;
        const left = emitExpression(node.args[0] as Node, divide);
        const right = emitExpression(node.args[1] as Node, divide + 1);
        return divide < minPrecedence ? `(${left} / ${right})` : `${left} / ${right}`;
      }
      const mapped = CALL_MAP[node.name];
      if (!mapped) {
        throw new TranspileError(`Unsupported function "${node.name}"`);
      }
      return `${mapped}(${node.args.map((arg) => emitExpression(arg)).join(', ')})`;
    }
    case 'assign':
      throw new TranspileError('Unsupported assignment in value position');
  }
}

function emitStatement(node: Node, out: string[]) {
  if (node.type === 'call' && node.name === SEQUENCE_CALL) {
    for (const entry of node.args) {
      emitStatement(entry, out);
    }
    return;
  }

  if (node.type !== 'assign') {
    throw new TranspileError('Unsupported expression statement');
  }

  // Chained assignment (`a.x = a.y = expr`) becomes two statements.
  if (node.value.type === 'assign') {
    emitStatement(node.value, out);
    emitStatement(
      {
        type: 'assign',
        operator: node.operator,
        target: node.target,
        value: node.value.target,
      },
      out,
    );
    return;
  }

  const target = node.target;
  if (target.type !== 'variable' && target.type !== 'megabuf') {
    throw new TranspileError('Unsupported assignment target');
  }
  const targetText = emitExpression(target);
  if (node.operator === '=') {
    out.push(`${targetText} = ${emitExpression(node.value)};`);
    return;
  }

  // `x += expr` becomes `x = x + expr`, so the right-hand side needs the
  // precedence of the expanded operator's right operand.
  const operator = node.operator[0] as string;
  const precedence = (BINARY_PRECEDENCE[operator] as number) + 1;
  out.push(
    `${targetText} = ${targetText} ${operator} ${emitExpression(node.value, precedence)};`,
  );
}

/** Converts one butterchurn equation string into EEL statements. */
export function transpileButterchurnEquations(source: string): TranspileResult {
  const trimmed = source.trim();
  if (!trimmed) {
    return { ok: true, statements: [] };
  }

  try {
    const parser = new Parser(tokenize(trimmed));
    const statements: string[] = [];
    for (const node of parser.parseProgram()) {
      emitStatement(node, statements);
    }
    return { ok: true, statements };
  } catch (error) {
    if (error instanceof TranspileError) {
      return { ok: false, reason: error.message };
    }
    return {
      ok: false,
      reason: error instanceof Error ? error.message : String(error),
    };
  }
}

export type ButterchurnEquationSource = {
  init_eqs_str?: string;
  frame_eqs_str?: string;
  pixel_eqs_str?: string;
  point_eqs_str?: string;
};

export type ButterchurnPresetEquations = {
  init: string[];
  perFrame: string[];
  perPixel: string[];
  waves: {
    index: number;
    init: string[];
    perFrame: string[];
    perPoint: string[];
  }[];
  shapes: { index: number; init: string[]; perFrame: string[] }[];
  unsupported: { scope: string; reason: string }[];
};

function convert(
  source: string | undefined,
  scope: string,
  unsupported: { scope: string; reason: string }[],
): string[] {
  if (!source?.trim()) {
    return [];
  }
  const result = transpileButterchurnEquations(source);
  if (!result.ok) {
    unsupported.push({ scope, reason: result.reason });
    return [];
  }
  return result.statements;
}

/** Converts every equation block of a converted butterchurn preset payload. */
export function transpileButterchurnPreset(preset: {
  init_eqs_str?: string;
  frame_eqs_str?: string;
  pixel_eqs_str?: string;
  waves?: ButterchurnEquationSource[];
  shapes?: ButterchurnEquationSource[];
}): ButterchurnPresetEquations {
  const unsupported: { scope: string; reason: string }[] = [];

  const waves = (preset.waves ?? []).map((wave, index) => ({
    index,
    init: convert(wave.init_eqs_str, `wave${index}.init`, unsupported),
    perFrame: convert(
      wave.frame_eqs_str,
      `wave${index}.per_frame`,
      unsupported,
    ),
    perPoint: convert(
      wave.point_eqs_str,
      `wave${index}.per_point`,
      unsupported,
    ),
  }));

  const shapes = (preset.shapes ?? []).map((shape, index) => ({
    index,
    init: convert(shape.init_eqs_str, `shape${index}.init`, unsupported),
    perFrame: convert(
      shape.frame_eqs_str,
      `shape${index}.per_frame`,
      unsupported,
    ),
  }));

  return {
    init: convert(preset.init_eqs_str, 'preset.init', unsupported),
    perFrame: convert(preset.frame_eqs_str, 'preset.per_frame', unsupported),
    perPixel: convert(preset.pixel_eqs_str, 'preset.per_pixel', unsupported),
    waves,
    shapes,
    unsupported,
  };
}
