import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { toyManifestSchema } from '../assets/js/data/toy-schema.ts';
import { loadToyRegistry } from './toy-registry.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');

export const GENERATED_TOY_MANIFEST_PATH = 'assets/js/data/toy-manifest.ts';
export const GENERATED_PUBLIC_TOYS_PATH = 'public/toys.json';

const manifestPath = path.join(repoRoot, GENERATED_TOY_MANIFEST_PATH);
const publicPath = path.join(repoRoot, GENERATED_PUBLIC_TOYS_PATH);

function formatZodIssues(error: {
  issues: { path: PropertyKey[]; message: string }[];
}) {
  return error.issues
    .map((issue) => {
      const pathLabel = issue.path.length
        ? issue.path
            .map((segment) =>
              typeof segment === 'symbol'
                ? segment.toString()
                : String(segment),
            )
            .join('.')
        : 'manifest';
      return `- ${pathLabel}: ${issue.message}`;
    })
    .join('\n');
}

export function buildManifestSource(data: unknown, sourceLabel: string) {
  const parsed = toyManifestSchema.safeParse(data);
  if (!parsed.success) {
    const message = [
      `Toy manifest validation failed for ${sourceLabel}:`,
      formatZodIssues(parsed.error),
    ].join('\n');
    throw new Error(message);
  }

  return parsed.data;
}

export function buildManifestModule(manifest: unknown) {
  const manifestJson = JSON.stringify(manifest, null, 2);
  return `/* This file is auto-generated by scripts/generate-toy-manifest.ts. */\nimport type { ToyManifest } from './toy-schema.ts';\n\nconst toyManifestJson = ${JSON.stringify(manifestJson)};\n\nexport const toyManifest: ToyManifest = JSON.parse(toyManifestJson) as ToyManifest;\n\nexport default toyManifest;\n`;
}

export function buildPublicToysJson(manifest: unknown) {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export async function writeManifestFiles(manifest: unknown) {
  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, buildManifestModule(manifest), 'utf8');
  await fs.writeFile(publicPath, buildPublicToysJson(manifest), 'utf8');
}

export async function generateToyArtifacts(root = repoRoot) {
  const { entries, relativePath } = await loadToyRegistry(root);
  const manifest = buildManifestSource(entries, relativePath);
  const manifestModule = buildManifestModule(manifest);
  const publicJson = buildPublicToysJson(manifest);

  if (root === repoRoot) {
    await writeManifestFiles(manifest);
  }

  return {
    manifest,
    manifestModule,
    publicJson,
  };
}

async function main() {
  await generateToyArtifacts(repoRoot);
  console.log('Generated toy manifest at assets/js/data/toy-manifest.ts.');
  console.log('Updated public/toys.json for runtime fetch overrides.');
}

const argvPath = process.argv[1] ? path.resolve(process.argv[1]) : '';
if (argvPath && import.meta.url === pathToFileURL(argvPath).href) {
  await main();
}
