/**
 * Generates the C++ harness's copy of the parity reference audio signal.
 *
 * `scripts/native-projectm-capture.cpp` and our own capture path must feed
 * byte-identical samples to projectM and to the Stims runtime, or a parity
 * diff is comparing two renderers that heard different music while reporting
 * the difference as a rendering gap. Hand-mirroring the constants in two
 * languages is exactly the kind of duplication that drifts silently — nothing
 * errors, every number just quietly becomes wrong — so the C++ side is
 * generated from `src/js/core/testing/reference-audio.ts`, which is the single
 * source of truth.
 *
 *   bun run scripts/generate-reference-audio-header.ts [--check]
 *
 * `--check` fails when the checked-in header no longer matches the TypeScript,
 * and runs as part of the quality gate.
 */
import fs from 'node:fs';
import path from 'node:path';
import {
  REFERENCE_AUDIO_SAMPLE_RATE,
  REFERENCE_AUDIO_SAMPLES_PER_FRAME,
  REFERENCE_AUDIO_TONES,
} from '../src/js/core/testing/reference-audio.ts';

const HEADER_PATH = path.join(
  process.cwd(),
  'scripts',
  'reference-audio-signal.h',
);

export function buildReferenceAudioHeader() {
  const tones = REFERENCE_AUDIO_TONES.map(
    (tone) =>
      `constexpr double k${tone.name}Hz = ${tone.hz.toFixed(1)};\n` +
      `constexpr double k${tone.name}Amp = ${tone.amp};`,
  ).join('\n');

  return `// GENERATED by scripts/generate-reference-audio-header.ts. Do not edit.
//
// Source of truth: src/js/core/testing/reference-audio.ts. Run
// \`bun run generate:reference-audio-header\` after changing it; the quality
// gate fails if this file drifts.
#pragma once

namespace stims_reference_audio {

constexpr int kSamplesPerFrame = ${REFERENCE_AUDIO_SAMPLES_PER_FRAME};
constexpr double kSampleRate = ${REFERENCE_AUDIO_SAMPLE_RATE}.0;

${tones}

inline double sampleAt(long long sampleIndex) {
  const double t = static_cast<double>(sampleIndex) / kSampleRate;
  const double twoPi = 6.283185307179586;
  return ${REFERENCE_AUDIO_TONES.map(
    (tone) => `k${tone.name}Amp * std::sin(twoPi * k${tone.name}Hz * t)`,
  ).join(' +\n         ')};
}

}  // namespace stims_reference_audio
`;
}

if (import.meta.main) {
  const generated = buildReferenceAudioHeader();
  const check = process.argv.includes('--check');
  const current = fs.existsSync(HEADER_PATH)
    ? fs.readFileSync(HEADER_PATH, 'utf8')
    : null;
  if (check) {
    if (current !== generated) {
      console.error(
        'scripts/reference-audio-signal.h is stale. The C++ harness would feed ' +
          'projectM different audio than our capture feeds the runtime, which ' +
          'invalidates every parity reference without erroring. Run ' +
          '`bun run generate:reference-audio-header`.',
      );
      process.exit(1);
    }
    console.log('reference audio header is current.');
  } else {
    fs.writeFileSync(HEADER_PATH, generated);
    console.log(`Wrote ${HEADER_PATH}`);
  }
}
