#!/usr/bin/env bun
/**
 * Generates `docs/GUARDRAILS.md` — the rules this repo enforces — from the
 * guard scripts themselves.
 *
 * The 25 `check:*` scripts encode the repo's unwritten rules, and most already
 * explain their own rationale in a docblock. That rationale was only reachable
 * by opening `scripts/`, so in practice contributors met each rule by tripping
 * it. This generator surfaces the explanations that already exist as one page a
 * person can read before writing code.
 *
 * Generated, not written, for the same reason `bun run help` is: a hand-kept
 * list of guards drifts the moment someone adds one, and a stale list of rules
 * is worse than none. `--check` fails when the committed page is out of date,
 * so the docblock is the single source of truth.
 *
 * Run `bun run generate:guardrails` to refresh, `--check` in the quality gate.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildGatePlan } from './run-quality-gate.ts';

const ROOT = process.cwd();
const OUT = join(ROOT, 'docs', 'GUARDRAILS.md');
const checkOnly = process.argv.includes('--check');

const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as {
  scripts?: Record<string, string>;
};
const scripts = pkg.scripts ?? {};

/**
 * Which gate each guard runs in, read from the gate plan itself rather than
 * from the composite command strings — `check:quick` and `check` both resolve
 * to `run-quality-gate.ts`, so membership is only knowable from its plan.
 */
const gateNames = (mode: 'quick' | 'full') => {
  const plan = buildGatePlan(mode, 'parallel');
  const steps = [...plan.preflight, ...plan.concurrent, ...plan.postflight];
  return new Set(
    steps
      .map((step) => step.cmd[step.cmd.indexOf('run') + 1])
      .filter((name): name is string => Boolean(name)),
  );
};
const quickGuards = gateNames('quick');
const fullGuards = gateNames('full');

function gateMembership(name: string): string {
  if (quickGuards.has(name)) return '`check:quick`';
  if (fullGuards.has(name)) return '`check`';
  return 'on demand';
}

/** Pulls the full docblock body (not just the first paragraph) from a script. */
function docblock(command: string): { summary: string; rest: string } | null {
  const match = command.match(/scripts\/([^\s/]+\.(?:ts|mjs|js))/u);
  if (!match) return null;
  let text: string;
  try {
    text = readFileSync(join(ROOT, 'scripts', match[1]), 'utf8');
  } catch {
    return null;
  }
  const lines = text.split(/\r?\n/u);
  const start = lines
    .slice(0, 10)
    .findIndex((line) => line.trimStart().startsWith('/**'));
  if (start === -1) return null;

  const body: string[] = [];
  for (const raw of lines.slice(start)) {
    if (raw.trimStart().startsWith('/**')) continue;
    if (raw.includes('*/')) break;
    body.push(raw.replace(/^\s*\*\s?/u, '').trimEnd());
  }
  // First paragraph is the summary; the remainder is the rationale.
  const blank = body.findIndex((line) => line.trim() === '');
  const summary = (blank === -1 ? body : body.slice(0, blank))
    .join(' ')
    .replace(/\s+/gu, ' ')
    .trim();
  const rest = (blank === -1 ? [] : body.slice(blank + 1)).join('\n').trim();
  return { summary, rest };
}

type Guard = { name: string; summary: string; rest: string; gate: string };

const guards: Guard[] = [];
const undocumented: string[] = [];

for (const [name, command] of Object.entries(scripts)) {
  if (!name.startsWith('check:')) continue;
  if (name === 'check' || name === 'check:quick' || name === 'check:all')
    continue;
  const doc = docblock(command);
  if (!doc?.summary) {
    undocumented.push(name);
    continue;
  }
  guards.push({
    name,
    summary: doc.summary,
    rest: doc.rest,
    gate: gateMembership(name),
  });
}

guards.sort((a, b) => a.name.localeCompare(b.name));

const lines: string[] = [
  '<!-- Generated by `bun run generate:guardrails`. Do not edit by hand:',
  '     each entry comes from the docblock atop its guard script. -->',
  '',
  '# What this repo enforces',
  '',
  'Stims has more automated rules than a newcomer can discover by reading code,',
  'and historically the only way to meet them was to trip one. This page is that',
  'set of rules, generated from the guards themselves so it cannot go stale.',
  '',
  'Run `bun run check:quick` early and often — it is seconds, and it is how these',
  'become fast feedback instead of a surprise at PR time.',
  '',
  '| Guard | Runs in | Enforces |',
  '| --- | --- | --- |',
];

for (const guard of guards) {
  const summary = guard.summary.replace(/\|/gu, '\\|');
  lines.push(
    `| [\`${guard.name}\`](#${guard.name.replace(':', '')}) | ${guard.gate} | ${summary} |`,
  );
}

lines.push('', '---', '');

for (const guard of guards) {
  lines.push(`## ${guard.name}`, '', guard.summary, '');
  if (guard.rest) lines.push(guard.rest, '');
  lines.push(`Run it directly: \`bun run ${guard.name}\``, '');
}

if (undocumented.length > 0) {
  lines.push(
    '---',
    '',
    '## Not yet documented',
    '',
    'These guards have no docblock to generate from, so their rationale still',
    'lives only in the code. Adding one here is a good first contribution:',
    '',
    ...undocumented.sort().map((name) => `- \`${name}\``),
    '',
  );
}

const rendered = `${lines
  .join('\n')
  .replace(/\n{3,}/gu, '\n\n')
  .trim()}\n`;

if (checkOnly) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    console.error(
      'docs/GUARDRAILS.md is missing. Run `bun run generate:guardrails`.',
    );
    process.exit(1);
  }
  if (current !== rendered) {
    console.error(
      'docs/GUARDRAILS.md is out of date with the guard docblocks.\n' +
        'Run `bun run generate:guardrails` and commit the result.',
    );
    process.exit(1);
  }
  console.log('docs/GUARDRAILS.md is current.');
  process.exit(0);
}

writeFileSync(OUT, rendered);
console.log(
  `Wrote docs/GUARDRAILS.md — ${guards.length} guards documented, ${undocumented.length} pending.`,
);
