import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  type ToyEntry,
  type ToyManifest,
  toyManifestSchema,
} from '../assets/js/data/toy-schema.ts';
import { loadToyRegistry } from './toy-registry.ts';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');

export const GENERATED_TOY_MANIFEST_PATH = 'assets/js/data/toy-manifest.ts';
export const GENERATED_PUBLIC_TOYS_PATH = 'public/toys.json';
export const GENERATED_TOY_SCRIPT_INDEX_PATH = 'docs/TOY_SCRIPT_INDEX.md';
export const GENERATED_TOY_NOTES_PATH = 'docs/toys.md';

const manifestPath = path.join(repoRoot, GENERATED_TOY_MANIFEST_PATH);
const publicPath = path.join(repoRoot, GENERATED_PUBLIC_TOYS_PATH);
const toyScriptIndexPath = path.join(repoRoot, GENERATED_TOY_SCRIPT_INDEX_PATH);
const toyNotesPath = path.join(repoRoot, GENERATED_TOY_NOTES_PATH);

function formatZodIssues(error: {
  issues: { path: PropertyKey[]; message: string }[];
}) {
  return error.issues
    .map((issue) => {
      const pathLabel = issue.path.length
        ? issue.path
            .map((segment) =>
              typeof segment === 'symbol'
                ? segment.toString()
                : String(segment),
            )
            .join('.')
        : 'manifest';
      return `- ${pathLabel}: ${issue.message}`;
    })
    .join('\n');
}

export function buildManifestSource(data: unknown, sourceLabel: string) {
  const parsed = toyManifestSchema.safeParse(data);
  if (!parsed.success) {
    const message = [
      `Toy manifest validation failed for ${sourceLabel}:`,
      formatZodIssues(parsed.error),
    ].join('\n');
    throw new Error(message);
  }

  return parsed.data;
}

export function buildManifestModule(manifest: unknown) {
  const manifestJson = JSON.stringify(manifest, null, 2);
  return `/* This file is auto-generated by scripts/generate-toy-manifest.ts. */\nimport type { ToyManifest } from './toy-schema.ts';\n\nexport const toyManifest: ToyManifest = ${manifestJson};\n\nexport default toyManifest;\n`;
}

export function buildPublicToysJson(manifest: unknown) {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function formatCapabilitySummary(entry: ToyEntry) {
  const enabledCapabilities = Object.entries(entry.capabilities)
    .filter(([, enabled]) => enabled)
    .map(([capability]) => capability);
  return enabledCapabilities.length > 0
    ? enabledCapabilities.join(', ')
    : 'none';
}

function formatRendererSummary(entry: ToyEntry) {
  if (entry.requiresWebGPU) {
    return entry.allowWebGLFallback
      ? 'WebGPU preferred with WebGL fallback'
      : 'WebGPU required';
  }
  return 'WebGL/WebGPU compatible';
}

function formatLaunchTargets(entry: ToyEntry) {
  if (entry.slug === 'milkdrop') {
    return '`/milkdrop/` (canonical) and `/milkdrop/?experience=milkdrop` (explicit deep link)';
  }
  return `\`/milkdrop/?experience=${entry.slug}\``;
}

function formatOptionalList(
  heading: string,
  items: string[] | undefined,
  indent = '',
) {
  if (!items || items.length === 0) {
    return '';
  }

  return [
    `${indent}${heading}`,
    ...items.map((item) => `${indent}- ${item}`),
    '',
  ].join('\n');
}

export function buildToyScriptIndex(manifest: ToyManifest) {
  const rows = manifest
    .map(
      (entry) =>
        `| \`${entry.slug}\` | \`${entry.module}\` | ${formatLaunchTargets(entry)} |`,
    )
    .join('\n');

  return `# Toy Script Index

This file is auto-generated by \`scripts/generate-toy-manifest.ts\`.
It reflects the current shipped entries from \`assets/data/toys.json\`.

## Active visualizer entries

| Slug | Entry module | How it loads |
| --- | --- | --- |
${rows}
`;
}

export function buildToyNotes(manifest: ToyManifest) {
  const sections = manifest
    .map((entry) => {
      const starterPreset = entry.starterPreset
        ? `- Starter preset: \`${entry.starterPreset.id}\` (${entry.starterPreset.label})`
        : '';
      const firstRunHint = entry.firstRunHint
        ? `- First-run hint: ${entry.firstRunHint}`
        : '';
      const wowControl = entry.wowControl
        ? `- Highlight control: ${entry.wowControl}`
        : '';
      const recommendedCapability = entry.recommendedCapability
        ? `- Recommended input: \`${entry.recommendedCapability}\``
        : '';
      const optionalLines = [
        starterPreset,
        firstRunHint,
        wowControl,
        recommendedCapability,
      ].filter(Boolean);

      return [
        `## ${entry.title} (\`${entry.slug}\`)`,
        '',
        `${entry.description}`,
        '',
        `- Entry module: \`${entry.module}\``,
        `- Launch route: ${formatLaunchTargets(entry)}`,
        `- Renderer support: ${formatRendererSummary(entry)}`,
        `- Lifecycle stage: \`${entry.lifecycleStage ?? 'unspecified'}\``,
        `- Capabilities: ${formatCapabilitySummary(entry)}`,
        ...(entry.moods?.length ? [`- Moods: ${entry.moods.join(', ')}`] : []),
        ...(entry.tags?.length ? [`- Tags: ${entry.tags.join(', ')}`] : []),
        ...optionalLines,
        '',
        formatOptionalList('### Controls', entry.controls),
        formatOptionalList('### Touch hints', entry.touchHints),
        formatOptionalList('### Desktop hints', entry.desktopHints),
      ]
        .filter((line) => line !== undefined && line !== null)
        .join('\n')
        .trimEnd();
    })
    .join('\n\n');

  return `# Toy Manifest Reference

This file is auto-generated by \`scripts/generate-toy-manifest.ts\`.
It summarizes the shipped visualizer entries from \`assets/data/toys.json\`.

${sections}
`;
}

export async function writeManifestFiles(manifest: ToyManifest) {
  await fs.mkdir(path.dirname(manifestPath), { recursive: true });
  await fs.writeFile(manifestPath, buildManifestModule(manifest), 'utf8');
  await fs.writeFile(publicPath, buildPublicToysJson(manifest), 'utf8');
  await fs.writeFile(toyScriptIndexPath, buildToyScriptIndex(manifest), 'utf8');
  await fs.writeFile(toyNotesPath, buildToyNotes(manifest), 'utf8');
}

export async function generateToyArtifacts(root = repoRoot) {
  const { entries, relativePath } = await loadToyRegistry(root);
  const manifest = buildManifestSource(entries, relativePath);
  const manifestModule = buildManifestModule(manifest);
  const publicJson = buildPublicToysJson(manifest);

  if (root === repoRoot) {
    await writeManifestFiles(manifest);
  }

  return {
    manifest,
    manifestModule,
    publicJson,
  };
}

async function main() {
  await generateToyArtifacts(repoRoot);
  console.log('Synced toy manifest artifacts from assets/data/toys.json.');
  console.log('Generated assets/js/data/toy-manifest.ts.');
  console.log('Generated public/toys.json.');
  console.log('Generated docs/TOY_SCRIPT_INDEX.md and docs/toys.md.');
}

const argvPath = process.argv[1] ? path.resolve(process.argv[1]) : '';
if (argvPath && import.meta.url === pathToFileURL(argvPath).href) {
  await main();
}
