// GENERATED by scripts/generate-reference-audio-header.ts. Do not edit.
//
// Source of truth: src/js/core/testing/reference-audio.ts. Run
// `bun run generate:reference-audio-header` after changing it; the quality
// gate fails if this file drifts.
#pragma once

namespace stims_reference_audio {

constexpr int kSamplesPerFrame = 1024;
constexpr double kSampleRate = 44100.0;

constexpr double kBassHz = 110.0;
constexpr double kBassAmp = 0.0707;
constexpr double kMidHz = 880.0;
constexpr double kMidAmp = 0.2025;
constexpr double kTrebHz = 5000.0;
constexpr double kTrebAmp = 0.627;

inline double sampleAt(long long sampleIndex) {
  const double t = static_cast<double>(sampleIndex) / kSampleRate;
  const double twoPi = 6.283185307179586;
  return kBassAmp * std::sin(twoPi * kBassHz * t) +
         kMidAmp * std::sin(twoPi * kMidHz * t) +
         kTrebAmp * std::sin(twoPi * kTrebHz * t);
}

}  // namespace stims_reference_audio
