import { describe, expect, test } from 'bun:test';
import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import {
  loadVisualReferenceManifest,
  VISUAL_REFERENCE_FIXTURE_ROOT,
  VISUAL_REFERENCE_MANIFEST_PATH,
} from '../../scripts/visual-reference-manifest.ts';

/**
 * Fixture roots, split by whether a clean checkout actually has them.
 *
 * `public/milkdrop-presets/previews/` is excluded from the repo on purpose
 * (.gitignore) — the 1,800-odd preview PNGs are generated by the preview
 * generator and served from R2, not committed. 39 of the manifest's 48
 * entries name an image that only ever lands there.
 *
 * The old test required every entry's image to exist on disk, which meant it
 * passed on any machine that had run the generator and failed on every fresh
 * clone. That is what it did in CI: red on four consecutive pushes for a
 * reason no local `bun run check` could reproduce. Asserting against
 * artifacts a clean checkout cannot have is the defect — not the CI runner.
 */
const COMMITTED_FIXTURE_ROOTS = {
  projectm: [VISUAL_REFERENCE_FIXTURE_ROOT],
  stims: ['tests/fixtures/milkdrop/stims-reference'],
} as const;

/** Populated by tooling, absent from a clean clone. */
const GENERATED_FIXTURE_ROOTS = [
  'public/milkdrop-presets/previews',
  'output/playwright/projectm-cream-compositor',
] as const;

describe('visual reference manifest', () => {
  const repoRoot = process.cwd();
  const manifest = loadVisualReferenceManifest(repoRoot);

  const committedRootsFor = (renderer: 'projectm' | 'stims') =>
    COMMITTED_FIXTURE_ROOTS[renderer].map((root) => path.join(repoRoot, root));

  const resolveIn = (roots: string[], file: string) =>
    roots.find((root) => existsSync(path.join(root, file))) ?? null;

  test('stays internally consistent', () => {
    expect(
      existsSync(path.join(repoRoot, VISUAL_REFERENCE_MANIFEST_PATH)),
    ).toBe(true);
    expect(existsSync(path.join(repoRoot, VISUAL_REFERENCE_FIXTURE_ROOT))).toBe(
      true,
    );
    expect(manifest.version).toBe(1);
    expect(manifest.parityTarget).toBe('projectm-visual-reference');
    expect(manifest.fixtureRoot).toBe(VISUAL_REFERENCE_FIXTURE_ROOT);
    expect(manifest.presetCount).toBe(manifest.presets.length);
    expect(manifest.presets.length).toBeGreaterThanOrEqual(
      manifest.minimumPresetCount,
    );

    const ids = manifest.presets.map((entry) => entry.id);
    expect(new Set(ids).size).toBe(ids.length);

    manifest.presets.forEach((entry) => {
      expect(entry.id.trim().length).toBeGreaterThan(0);
      expect(entry.title.trim().length).toBeGreaterThan(0);
      expect(entry.sourceFamily.trim().length).toBeGreaterThan(0);
      expect(entry.provenance.label.trim().length).toBeGreaterThan(0);
      expect(entry.provenance.importedAt.trim().length).toBeGreaterThan(0);
      expect(['projectm', 'stims']).toContain(entry.capture.renderer);
      expect(entry.capture.width).toBeGreaterThan(0);
      expect(entry.capture.height).toBeGreaterThan(0);
      expect(entry.capture.warmupMs).toBeGreaterThanOrEqual(0);
      expect(entry.capture.captureOffsetMs).toBeGreaterThanOrEqual(0);
      expect(entry.tolerance.profile.trim().length).toBeGreaterThan(0);
      expect(entry.tolerance.threshold).toBeGreaterThanOrEqual(0);
      expect(entry.tolerance.failThreshold).toBeGreaterThanOrEqual(0);
      // Catches a typo'd or path-traversing image name without needing the
      // file, which is the only structural check available in a clean clone.
      expect(entry.image).toMatch(/^[\w.-]+\.(?:png|jpg|jpeg)$/u);
      expect(entry.image).not.toContain('..');
    });
  });

  test('every projectm reference image is committed', () => {
    // These are the actual parity baselines — captured from projectM, not
    // reproducible by running our own tooling — so they must be in the repo.
    const projectmEntries = manifest.presets.filter(
      (entry) => entry.capture.renderer === 'projectm',
    );
    expect(projectmEntries.length).toBeGreaterThan(0);

    const missing = projectmEntries.filter(
      (entry) => resolveIn(committedRootsFor('projectm'), entry.image) === null,
    );
    expect(missing.map((entry) => entry.image)).toEqual([]);
  });

  test('enough entries are backed by committed fixtures to be worth running', () => {
    const committed = manifest.presets.filter(
      (entry) =>
        resolveIn(committedRootsFor(entry.capture.renderer), entry.image) !==
        null,
    );
    // Guards against the manifest drifting to entirely generated artifacts,
    // which would leave a clean checkout with no baseline at all.
    expect(committed.length).toBeGreaterThanOrEqual(
      manifest.minimumPresetCount,
    );
  });

  test('entries without a committed fixture resolve once the generator has run', () => {
    // Full strength on a developer machine: if the previews directory is
    // populated, every remaining entry must resolve, so a typo'd filename
    // still fails here. Skipped only where the artifacts genuinely are not
    // present — a fresh clone or CI.
    //
    // The trigger is specifically the previews directory being non-empty,
    // not "any generated root exists": output/playwright/ survives an
    // unrelated local run, and treating that as proof the previews were
    // generated demanded 29 images the machine did not have.
    const previewsRoot = path.join(repoRoot, GENERATED_FIXTURE_ROOTS[0]);
    if (!existsSync(previewsRoot) || readdirSync(previewsRoot).length === 0) {
      // Nothing generated here, so the only thing left to check is that the
      // committed half still resolves — asserted rather than returning with
      // no expectation at all, which would read as a silent pass.
      const committedMissing = manifest.presets.filter((entry) => {
        const roots = committedRootsFor(entry.capture.renderer);
        return (
          roots.some((root) => existsSync(root)) &&
          resolveIn(roots, entry.image) === null &&
          entry.capture.renderer === 'projectm'
        );
      });
      expect(committedMissing.map((entry) => entry.image)).toEqual([]);
      return;
    }

    const generatedRoots = GENERATED_FIXTURE_ROOTS.map((root) =>
      path.join(repoRoot, root),
    ).filter((root) => existsSync(root));

    const unresolved = manifest.presets.filter((entry) => {
      const roots = [
        ...committedRootsFor(entry.capture.renderer),
        ...generatedRoots,
      ];
      return resolveIn(roots, entry.image) === null;
    });
    expect(unresolved.map((entry) => entry.image)).toEqual([]);
  });

  test('declared metadata sidecars resolve wherever their image does', () => {
    manifest.presets.forEach((entry) => {
      if (!entry.metadata) return;
      const roots = [
        ...committedRootsFor(entry.capture.renderer),
        ...GENERATED_FIXTURE_ROOTS.map((root) => path.join(repoRoot, root)),
      ].filter((root) => existsSync(root));

      const imageRoot = resolveIn(roots, entry.image);
      if (imageRoot === null) return;
      expect(existsSync(path.join(imageRoot, entry.metadata))).toBe(true);
    });
  });
});
